### ISSUE TITLE
Long running Idempotent task keeps creating watches and leads to Out Of Memory issues

### ISSUE THREAD

**Issue by gs-psharma** [nirmata/workflow#44]
SimpleQueue lists queued task and sets watcher to watch for new events in case of empty but if task is present and its picked up by some worker its not deleted in case of idempotent and all other workers goes into loop of watching again and again. If this single task is long processing other workers or threads if multithreaded keeps creating watcher instances.

**Comment by gs-psharma** [comment]
please release version with this fix

**Comment by Randgalt** [comment]
@dtoledo67 or @JimBugwadia will you release or do I need to?

**Comment by dtoledo67** [comment]
Hi Jordan,

I'll try to release it.

Thanks,

Damien

**Comment by dtoledo67** [comment]
I released nirmata-workflow:0.9.6 but the pom file is missing. I am not
sure how it happened.

Damien

**Comment by gs-psharma** [comment]
version is available on maven repository but doesnt have changes of fix, please re-release this 🙏

**Comment by Randgalt** [comment]
OK - I just released 0.9.7 - I don't know what happened with 0.9.6. Please let me know if this works.

**Comment by gs-psharma** [comment]
Yes @Randgalt  0.9.7 worked, Thank you
